name: "CI workflow"
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: "read"
jobs:

  composer:
    name: "Composer config validation"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Validate composer.json"
        run: "composer validate --strict"

  php:
    name: "PHP tests"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php_version:
          - "7.2"
          - "7.4"
    env:
      CC_TEST_REPORTER_ID: "c8bc13b8787c6de68ae094688dec7fd7bb3a14445d560194b5785fae2623d489"

    steps:
      - name: "GIT checkout"
        uses: "actions/checkout@v3"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php_version }}"
          coverage: "xdebug"

      - name: "Check PHP version"
        run: "php -v"

      - name: "PHP syntax validation"
        run: |
          php -l src/
          php -l tests/

      - name: "Composer install dependencies"
        run: "composer install --prefer-dist --no-progress"

      - name: "CodeClimate Reporter Setup"
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: "PHPUnit tests"
        run: |
          php vendor/bin/phpunit --coverage-clover clover.xml --coverage-text 
          ./cc-test-reporter after-build -t clover --exit-code $?
